# Generated by Django 2.0.6 on 2018-07-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontuser', '0003_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(db_index=True, default='s', max_length=7),
            preserve_default=False,
        ),
    ]
